import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

import { Github } from 'lucide-react';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        {/* Header */}
        <header className="w-full border-b bg-background">
          <div className="max-w-2xl mx-auto px-4 py-4">
            <Link href="/" className="text-xl font-bold hover:underline focus-visible:underline transition-colors">
              Blog
            </Link>
          </div>
        </header>
        {/* Main */}
        <main className="flex-1 w-full">
          <div className="max-w-2xl mx-auto px-4 py-8">{children}</div>
        </main>
        {/* Footer */}
        <footer className="w-full border-t bg-background">
          <div className="max-w-2xl mx-auto px-4 py-4 flex items-center justify-between text-sm text-muted-foreground">
            <span>© funai</span>
            <a
              href="https://github.com/paveg/blog-with-ai"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="GitHub Repository"
              className="inline-flex items-center justify-center rounded-full p-2 hover:text-primary transition-colors"
            >
              <Github className="h-6 w-6" />
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}
